CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_BOARD_COMPAT=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Bluetooth強度最大
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 0.4.0用バッテリープロキシ
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
