CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
# 左右の子機（LとR）を無線で受け入れる
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB_BOOT=y
CONFIG_ZMK_KEYBOARD_NAME="conductor"

# 0.6.1負荷軽減
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_USB_LOGGING=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
