CONFIG_ZMK_KEYBOARD_NAME="conductor"
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# 一旦眠らせます
CONFIG_ZMK_RGBLED_WIDGET=y
# CONFIG_ZMK_RGBLED_WIDGET_INTERVAL_MS=250

# マウス機能を親機で有効化（必須）
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_POINTING=y

# 0.6.1負荷軽減
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_USB_LOGGING=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 🌟 LEDピンと競合する可能性のある機能をオフにする
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=n

# 🌟 LED出力を有効化するための設定（念のため追加）
CONFIG_GPIO=y
