# 子機としての設定
CONFIG_ZMK_SPLIT=y
# CENTRALではない（＝子機）ことを明示
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# 電力を節約しつつ電波を強くする
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# スリープ設定（電池持ちのため推奨）
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
