CONFIG_ZMK_KEYBOARD_NAME="conductor"
CONFIG_ZMK_INPUT_SPLIT=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# --- 基本機能 ---
# CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_BLE=y
CONFIG_SPI=y
CONFIG_INPUT=y

# CONFIG_PMW3610_ALT=y
CONFIG_ZMK_POINTING=y

# --- ZMK Studio & その他機能 ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# バッテリーレポート設定
CONFIG_ZMK_BATTERY_REPORTING=y
# CONFIG_ZMK_BACKLIGHT_LOW_BAT_INDICATE=y
# CONFIG_ZMK_BACKLIGHT_LOW_BAT_PCT=10

CONFIG_BT_BAS=y

CONFIG_BT_BUF_ACL_TX_COUNT=30
CONFIG_BT_BUF_EVT_RX_COUNT=35
CONFIG_BT_L2CAP_TX_MTU=247

# トラックボールの大量データによるフリーズを防ぐため、作業メモリを大幅に拡張する
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# --- 🌟 バックライト機能（スレイブ側） ---
CONFIG_ZMK_BACKLIGHT=y
CONFIG_LED=y
CONFIG_LED_PWM=y
CONFIG_PWM=y
CONFIG_ZMK_BACKLIGHT_BRT_START=100
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=1000

# 通信最適化
# 通信間隔の最小値 最短は6 (7.5ms) (6)
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
# 通信間隔の最大値 最短は12 (15ms)(12)
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
# スレーブレーテンシ データがない時は通信をサボる（スキップする）(30回（15ms × 30回 ＝ 約0.45秒）)
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
# タイムアウト時間（単位は10ms） 400なら4秒(400)
# CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

