include:
  - board: xiao_ble//zmk
    shield: monokey_R rgbled_adapter
    snippets: [studio-rpc-usb-uart]
    artifact-name: monokey_C_add_dongle
  - board: xiao_ble//zmk
    shield: monokey_L rgbled_adapter
    artifact-name: monokey_C_add_dongle
  - board: xiao_ble//zmk
    shield: monokey_C rgbled_adapter
    snippets: [studio-rpc-usb-uart]
    artifact-name: monokey_C_add_dongle
  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset
